# Complete surah data
SURAH_DATA = [
    {"number": 1, "name": "Al-Fatiha", "englishName": "The Opening", "numberOfAyahs": 7, "revelationType": "Meccan"},
    {"number": 2, "name": "Al-Baqarah", "englishName": "The Cow", "numberOfAyahs": 286, "revelationType": "Medinan"},
    {"number": 3, "name": "Aal-Imran", "englishName": "Family of Imran", "numberOfAyahs": 200, "revelationType": "Medinan"},
    {"number": 4, "name": "An-Nisa", "englishName": "The Women", "numberOfAyahs": 176, "revelationType": "Medinan"},
    {"number": 5, "name": "Al-Ma'idah", "englishName": "The Table Spread", "numberOfAyahs": 120, "revelationType": "Medinan"},
    {"number": 6, "name": "Al-An'am", "englishName": "The Cattle", "numberOfAyahs": 165, "revelationType": "Meccan"},
    {"number": 7, "name": "Al-A'raf", "englishName": "The Heights", "numberOfAyahs": 206, "revelationType": "Meccan"},
    {"number": 8, "name": "Al-Anfal", "englishName": "The Spoils of War", "numberOfAyahs": 75, "revelationType": "Medinan"},
    {"number": 9, "name": "At-Tawbah", "englishName": "The Repentance", "numberOfAyahs": 129, "revelationType": "Medinan"},
    {"number": 10, "name": "Yunus", "englishName": "Jonah", "numberOfAyahs": 109, "revelationType": "Meccan"},
    {"number": 11, "name": "Hud", "englishName": "Hud", "numberOfAyahs": 123, "revelationType": "Meccan"},
    {"number": 12, "name": "Yusuf", "englishName": "Joseph", "numberOfAyahs": 111, "revelationType": "Meccan"},
    {"number": 13, "name": "Ar-Ra'd", "englishName": "The Thunder", "numberOfAyahs": 43, "revelationType": "Medinan"},
    {"number": 14, "name": "Ibrahim", "englishName": "Abraham", "numberOfAyahs": 52, "revelationType": "Meccan"},
    {"number": 15, "name": "Al-Hijr", "englishName": "The Rocky Tract", "numberOfAyahs": 99, "revelationType": "Meccan"},
    {"number": 16, "name": "An-Nahl", "englishName": "The Bee", "numberOfAyahs": 128, "revelationType": "Meccan"},
    {"number": 17, "name": "Al-Isra", "englishName": "The Night Journey", "numberOfAyahs": 111, "revelationType": "Meccan"},
    {"number": 18, "name": "Al-Kahf", "englishName": "The Cave", "numberOfAyahs": 110, "revelationType": "Meccan"},
    {"number": 19, "name": "Maryam", "englishName": "Mary", "numberOfAyahs": 98, "revelationType": "Meccan"},
    {"number": 20, "name": "Ta-Ha", "englishName": "Ta-Ha", "numberOfAyahs": 135, "revelationType": "Meccan"},
    {"number": 21, "name": "Al-Anbya", "englishName": "The Prophets", "numberOfAyahs": 112, "revelationType": "Meccan"},
    {"number": 22, "name": "Al-Hajj", "englishName": "The Pilgrimage", "numberOfAyahs": 78, "revelationType": "Medinan"},
    {"number": 23, "name": "Al-Mu'minun", "englishName": "The Believers", "numberOfAyahs": 118, "revelationType": "Meccan"},
    {"number": 24, "name": "An-Nur", "englishName": "The Light", "numberOfAyahs": 64, "revelationType": "Medinan"},
    {"number": 25, "name": "Al-Furqan", "englishName": "The Criterion", "numberOfAyahs": 77, "revelationType": "Meccan"},
    {"number": 26, "name": "Ash-Shu'ara", "englishName": "The Poets", "numberOfAyahs": 227, "revelationType": "Meccan"},
    {"number": 27, "name": "An-Naml", "englishName": "The Ant", "numberOfAyahs": 93, "revelationType": "Meccan"},
    {"number": 28, "name": "Al-Qasas", "englishName": "The Stories", "numberOfAyahs": 88, "revelationType": "Meccan"},
    {"number": 29, "name": "Al-Ankabut", "englishName": "The Spider", "numberOfAyahs": 69, "revelationType": "Meccan"},
    {"number": 30, "name": "Ar-Rum", "englishName": "The Romans", "numberOfAyahs": 60, "revelationType": "Meccan"},
    {"number": 31, "name": "Luqman", "englishName": "Luqman", "numberOfAyahs": 34, "revelationType": "Meccan"},
    {"number": 32, "name": "As-Sajdah", "englishName": "The Prostration", "numberOfAyahs": 30, "revelationType": "Meccan"},
    {"number": 33, "name": "Al-Ahzab", "englishName": "The Combined Forces", "numberOfAyahs": 73, "revelationType": "Medinan"},
    {"number": 34, "name": "Saba", "englishName": "Sheba", "numberOfAyahs": 54, "revelationType": "Meccan"},
    {"number": 35, "name": "Fatir", "englishName": "Originator", "numberOfAyahs": 45, "revelationType": "Meccan"},
    {"number": 36, "name": "Ya-Sin", "englishName": "Ya-Sin", "numberOfAyahs": 83, "revelationType": "Meccan"},
    {"number": 37, "name": "As-Saffat", "englishName": "Those who set the Ranks", "numberOfAyahs": 182, "revelationType": "Meccan"},
    {"number": 38, "name": "Sad", "englishName": "Sad", "numberOfAyahs": 88, "revelationType": "Meccan"},
    {"number": 39, "name": "Az-Zumar", "englishName": "The Troops", "numberOfAyahs": 75, "revelationType": "Meccan"},
    {"number": 40, "name": "Ghafir", "englishName": "The Forgiver", "numberOfAyahs": 85, "revelationType": "Meccan"},
    {"number": 41, "name": "Fussilat", "englishName": "Explained in Detail", "numberOfAyahs": 54, "revelationType": "Meccan"},
    {"number": 42, "name": "Ash-Shuraa", "englishName": "The Consultation", "numberOfAyahs": 53, "revelationType": "Meccan"},
    {"number": 43, "name": "Az-Zukhruf", "englishName": "The Ornaments of Gold", "numberOfAyahs": 89, "revelationType": "Meccan"},
    {"number": 44, "name": "Ad-Dukhan", "englishName": "The Smoke", "numberOfAyahs": 59, "revelationType": "Meccan"},
    {"number": 45, "name": "Al-Jathiyah", "englishName": "The Kneeling", "numberOfAyahs": 37, "revelationType": "Meccan"},
    {"number": 46, "name": "Al-Ahqaf", "englishName": "The Wind-Curved Sandhills", "numberOfAyahs": 35, "revelationType": "Meccan"},
    {"number": 47, "name": "Muhammad", "englishName": "Muhammad", "numberOfAyahs": 38, "revelationType": "Medinan"},
    {"number": 48, "name": "Al-Fath", "englishName": "The Victory", "numberOfAyahs": 29, "revelationType": "Medinan"},
    {"number": 49, "name": "Al-Hujurat", "englishName": "The Private Apartments", "numberOfAyahs": 18, "revelationType": "Medinan"},
    {"number": 50, "name": "Qaf", "englishName": "Qaf", "numberOfAyahs": 45, "revelationType": "Meccan"},
    {"number": 51, "name": "Adh-Dhariyat", "englishName": "The Winnowing Winds", "numberOfAyahs": 60, "revelationType": "Meccan"},
    {"number": 52, "name": "At-Tur", "englishName": "The Mount", "numberOfAyahs": 49, "revelationType": "Meccan"},
    {"number": 53, "name": "An-Najm", "englishName": "The Star", "numberOfAyahs": 62, "revelationType": "Meccan"},
    {"number": 54, "name": "Al-Qamar", "englishName": "The Moon", "numberOfAyahs": 55, "revelationType": "Meccan"},
    {"number": 55, "name": "Ar-Rahman", "englishName": "The Beneficent", "numberOfAyahs": 78, "revelationType": "Medinan"},
    {"number": 56, "name": "Al-Waqi'ah", "englishName": "The Inevitable", "numberOfAyahs": 96, "revelationType": "Meccan"},
    {"number": 57, "name": "Al-Hadid", "englishName": "The Iron", "numberOfAyahs": 29, "revelationType": "Medinan"},
    {"number": 58, "name": "Al-Mujadila", "englishName": "The Pleading Woman", "numberOfAyahs": 22, "revelationType": "Medinan"},
    {"number": 59, "name": "Al-Hashr", "englishName": "The Exile", "numberOfAyahs": 24, "revelationType": "Medinan"},
    {"number": 60, "name": "Al-Mumtahanah", "englishName": "The Woman to be Examined", "numberOfAyahs": 13, "revelationType": "Medinan"},
    {"number": 61, "name": "As-Saf", "englishName": "The Ranks", "numberOfAyahs": 14, "revelationType": "Medinan"},
    {"number": 62, "name": "Al-Jumu'ah", "englishName": "The Congregation", "numberOfAyahs": 11, "revelationType": "Medinan"},
    {"number": 63, "name": "Al-Munafiqun", "englishName": "The Hypocrites", "numberOfAyahs": 11, "revelationType": "Medinan"},
    {"number": 64, "name": "At-Taghabun", "englishName": "The Mutual Disillusion", "numberOfAyahs": 18, "revelationType": "Medinan"},
    {"number": 65, "name": "At-Talaq", "englishName": "Divorce", "numberOfAyahs": 12, "revelationType": "Medinan"},
    {"number": 66, "name": "At-Tahrim", "englishName": "The Prohibition", "numberOfAyahs": 12, "revelationType": "Medinan"},
    {"number": 67, "name": "Al-Mulk", "englishName": "The Sovereignty", "numberOfAyahs": 30, "revelationType": "Meccan"},
    {"number": 68, "name": "Al-Qalam", "englishName": "The Pen", "numberOfAyahs": 52, "revelationType": "Meccan"},
    {"number": 69, "name": "Al-Haqqah", "englishName": "The Reality", "numberOfAyahs": 52, "revelationType": "Meccan"},
    {"number": 70, "name": "Al-Ma'arij", "englishName": "The Ascending Stairways", "numberOfAyahs": 44, "revelationType": "Meccan"},
    {"number": 71, "name": "Nuh", "englishName": "Noah", "numberOfAyahs": 28, "revelationType": "Meccan"},
    {"number": 72, "name": "Al-Jinn", "englishName": "The Jinn", "numberOfAyahs": 28, "revelationType": "Meccan"},
    {"number": 73, "name": "Al-Muzzammil", "englishName": "The Enshrouded One", "numberOfAyahs": 20, "revelationType": "Meccan"},
    {"number": 74, "name": "Al-Muddathir", "englishName": "The Cloaked One", "numberOfAyahs": 56, "revelationType": "Meccan"},
    {"number": 75, "name": "Al-Qiyamah", "englishName": "The Resurrection", "numberOfAyahs": 40, "revelationType": "Meccan"},
    {"number": 76, "name": "Al-Insan", "englishName": "Man", "numberOfAyahs": 31, "revelationType": "Medinan"},
    {"number": 77, "name": "Al-Mursalat", "englishName": "The Emissaries", "numberOfAyahs": 50, "revelationType": "Meccan"},
    {"number": 78, "name": "An-Naba", "englishName": "The Tidings", "numberOfAyahs": 40, "revelationType": "Meccan"},
    {"number": 79, "name": "An-Nazi'at", "englishName": "Those who drag forth", "numberOfAyahs": 46, "revelationType": "Meccan"},
    {"number": 80, "name": "Abasa", "englishName": "He frowned", "numberOfAyahs": 42, "revelationType": "Meccan"},
    {"number": 81, "name": "At-Takwir", "englishName": "The Overthrowing", "numberOfAyahs": 29, "revelationType": "Meccan"},
    {"number": 82, "name": "Al-Infitar", "englishName": "The Cleaving", "numberOfAyahs": 19, "revelationType": "Meccan"},
    {"number": 83, "name": "Al-Mutaffifin", "englishName": "The Defrauding", "numberOfAyahs": 36, "revelationType": "Meccan"},
    {"number": 84, "name": "Al-Inshiqaq", "englishName": "The Splitting Open", "numberOfAyahs": 25, "revelationType": "Meccan"},
    {"number": 85, "name": "Al-Buruj", "englishName": "The Mansions of the Stars", "numberOfAyahs": 22, "revelationType": "Meccan"},
    {"number": 86, "name": "At-Tariq", "englishName": "The Morning Star", "numberOfAyahs": 17, "revelationType": "Meccan"},
    {"number": 87, "name": "Al-A'la", "englishName": "The Most High", "numberOfAyahs": 19, "revelationType": "Meccan"},
    {"number": 88, "name": "Al-Ghashiyah", "englishName": "The Overwhelming", "numberOfAyahs": 26, "revelationType": "Meccan"},
    {"number": 89, "name": "Al-Fajr", "englishName": "The Dawn", "numberOfAyahs": 30, "revelationType": "Meccan"},
    {"number": 90, "name": "Al-Balad", "englishName": "The City", "numberOfAyahs": 20, "revelationType": "Meccan"},
    {"number": 91, "name": "Ash-Shams", "englishName": "The Sun", "numberOfAyahs": 15, "revelationType": "Meccan"},
    {"number": 92, "name": "Al-Layl", "englishName": "The Night", "numberOfAyahs": 21, "revelationType": "Meccan"},
    {"number": 93, "name": "Ad-Duha", "englishName": "The Morning Hours", "numberOfAyahs": 11, "revelationType": "Meccan"},
    {"number": 94, "name": "Ash-Sharh", "englishName": "The Relief", "numberOfAyahs": 8, "revelationType": "Meccan"},
    {"number": 95, "name": "At-Tin", "englishName": "The Fig", "numberOfAyahs": 8, "revelationType": "Meccan"},
    {"number": 96, "name": "Al-'Alaq", "englishName": "The Clot", "numberOfAyahs": 19, "revelationType": "Meccan"},
    {"number": 97, "name": "Al-Qadr", "englishName": "The Power", "numberOfAyahs": 5, "revelationType": "Meccan"},
    {"number": 98, "name": "Al-Bayyinah", "englishName": "The Clear Proof", "numberOfAyahs": 8, "revelationType": "Medinan"},
    {"number": 99, "name": "Az-Zalzalah", "englishName": "The Earthquake", "numberOfAyahs": 8, "revelationType": "Medinan"},
    {"number": 100, "name": "Al-'Adiyat", "englishName": "The Coursers", "numberOfAyahs": 11, "revelationType": "Meccan"},
    {"number": 101, "name": "Al-Qari'ah", "englishName": "The Calamity", "numberOfAyahs": 11, "revelationType": "Meccan"},
    {"number": 102, "name": "At-Takathur", "englishName": "The Rivalry in world increase", "numberOfAyahs": 8, "revelationType": "Meccan"},
    {"number": 103, "name": "Al-'Asr", "englishName": "The Declining Day", "numberOfAyahs": 3, "revelationType": "Meccan"},
    {"number": 104, "name": "Al-Humazah", "englishName": "The Traducer", "numberOfAyahs": 9, "revelationType": "Meccan"},
    {"number": 105, "name": "Al-Fil", "englishName": "The Elephant", "numberOfAyahs": 5, "revelationType": "Meccan"},
    {"number": 106, "name": "Quraish", "englishName": "Quraish", "numberOfAyahs": 4, "revelationType": "Meccan"},
    {"number": 107, "name": "Al-Ma'un", "englishName": "The Small kindnesses", "numberOfAyahs": 7, "revelationType": "Meccan"},
    {"number": 108, "name": "Al-Kawthar", "englishName": "The Abundance", "numberOfAyahs": 3, "revelationType": "Meccan"},
    {"number": 109, "name": "Al-Kafirun", "englishName": "The Disbelievers", "numberOfAyahs": 6, "revelationType": "Meccan"},
    {"number": 110, "name": "An-Nasr", "englishName": "The Divine Support", "numberOfAyahs": 3, "revelationType": "Medinan"},
    {"number": 111, "name": "Al-Masad", "englishName": "The Palm Fiber", "numberOfAyahs": 5, "revelationType": "Meccan"},
    {"number": 112, "name": "Al-Ikhlas", "englishName": "The Sincerity", "numberOfAyahs": 4, "revelationType": "Meccan"},
    {"number": 113, "name": "Al-Falaq", "englishName": "The Daybreak", "numberOfAyahs": 5, "revelationType": "Meccan"},
    {"number": 114, "name": "An-Nas", "englishName": "Mankind", "numberOfAyahs": 6, "revelationType": "Meccan"}
]

# Application constants
MAX_DAILY_AYATS = 10
MIN_DAILY_AYATS = 1
MAX_USERNAME_LENGTH = 50
MIN_USERNAME_LENGTH = 3
MAX_PASSWORD_LENGTH = 128
MIN_PASSWORD_LENGTH = 6

# Achievement thresholds
ACHIEVEMENTS = {
    "week_warrior": {"streak": 7, "name": "Week Warrior"},
    "month_master": {"streak": 30, "name": "Month Master"},
    "century_champion": {"streak": 100, "name": "Century Champion"},
    "hundred_verses": {"verses": 100, "name": "Hundred Verses"},
    "thousand_verses": {"verses": 1000, "name": "Thousand Verses"}
}

# Rate limiting
RATE_LIMIT_PER_MINUTE = 60
RATE_LIMIT_PER_HOUR = 1000

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100 